
- name: install dependencies
  yum: name={{item}} update_cache=yes state=present
  with_items:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker repository
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker CE
  yum: name=docker-ce update_cache=yes state=present

- name: install dependencies for docker API
  yum: name={{item}} update_cache=yes state=present
  with_items:
    - python
    - python-pip

- name: install docker-py
  pip: name=docker-py state=present

- name: ensure docker engine is running
  service: name=docker.service state=restarted enabled=yes

- include: "run.yml"