- name: install dependencies
  apt: name={{item}} update_cache=yes state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python
    - python-pip

- name: add docker repository
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: install docker CE
  apt: name=docker-ce update_cache=yes state=present

- name: install docker-py
  pip: name=docker-py state=present

- name: ensure docker engine is running
  service: name=docker.service state=restarted enabled=yes

- include: "run.yml"