- name: install dependencies
  yum: name={{item}} state=installed
  with_items:
    - easy-rsa

- name: install OpenVPN server
  yum: name=openvpn state=installed

- name: create keys dir
  file: path=/etc/openvpn/easy-rsa/keys state=directory

- name: make key generation scripts available
  shell: "cp -rf /usr/share/easy-rsa/2.0/* /etc/openvpn/easy-rsa"

- name: copy easy-rsa vars
  copy: src=easy-rsa-vars dest=/etc/openvpn/easy-rsa/vars

- name: expose openssl config
  shell: cp /etc/openvpn/easy-rsa/openssl-1.0.0.cnf /etc/openvpn/easy-rsa/openssl.cnf

- name: generate server keys
  shell: |
    cd /etc/openvpn/easy-rsa
    source ./vars
    ./clean-all
    ./build-ca --batch
    ./build-key-server --batch server
    ./build-dh --batch
    openvpn --genkey --secret keys/ta.key
    cd /etc/openvpn/easy-rsa/keys
    cp dh2048.pem ca.crt ca.key server.crt server.key ta.key /etc/openvpn/

- name: generate client keys
  shell: |
    cd /etc/openvpn/easy-rsa
    source ./vars
    ./build-key --batch client

- name: configure OpenVPN server
  template: src=openvpn-server.conf dest=/etc/openvpn/server.conf
  notify: restart openvpn

- name: copy iptables rules
  template: src=iptables.rules dest=/root/iptables.sh mode=0700

- name: install iptables rules
  shell: /root/iptables.sh

#- name: preparing tor routes
#  debug: msg="+ gw {{ tor_ip }}  - gw {{ netgw }}"

#- name: check if tor routes are installed
#  command: ip route show via {{ tor_ip }}
#  register: route_installed

#- name: out
#  debug: msg={{ route_installed.stdout }}

#- name: configure tor routes
#  shell: |
#    route add default gw {{ tor_ip }}
#route add -net {{ net }} netmask {{ netmask }} gw {{ netgw }}
#route del default gw {{ netgw }}
#  when: "'default' not in route_installed.stdout"

